PURCHASE PLANNER FINAL PR
marvin-nyalik/BudgetApp pull request #8
Opened 2023-10-17 13:46 UTC by marvin-nyalik

Dear reviewer,

This is my PR for the Ruby on Rails capstone project. Here's a list of what I have done in this project:
- Splash screen

   A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- Sign up and log in pages

   The user should be able to register in the app with full name, email and password (all mandatory).
   The user can log into the app using email and password.
   If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- Home page (categories page)

   When the user logs in, they are presented with the categories page.
   For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that 
   category.
   When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
   There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- Transactions page

   For a given category, the list of transactions is presented, ordered by the most recent.
   At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions 
   in that category).
   There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
   When the user clicks on the "Back" button (<), the user navigates to the home page.

- "Add a new category" page

    The user fills out a form to create a new category, indicating their name and icon (both mandatory).
    The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
    When the user clicks on the "Back" button (<), the user navigates to the home page.

-  "Add a new transaction" page

     The user fills out a form to create a new transaction with:
        name (mandatory)
       amount (mandatory)
       categories (mandatory at least one)
       The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that 
       category.
       When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

- I also created unit and integration tests for all the most important components of this application.

Let me know if there are any changes required 👍

2023-10-17 15:31 UTC, zieeco requested changes
Hi @marvin-nyalik ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Nice project implmentation.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img height="80" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-17 15:31 UTC, zieeco commented on app/views/static_pages/splash.html.erb
> +</div>
- Hey, let's improve our design as your design doesn't seem to follow the main design. please, consider making these changes to improve your design:

   - the tow buttons are at the bottom of the container alinged vertically taking the full width with a text content of login and sign up.

*main design*
![image](https://github.com/marvin-nyalik/BudgetApp/assets/59397159/a35650f3-048d-46b9-8d24-be384cecec43)


*your design*
![image](https://github.com/marvin-nyalik/BudgetApp/assets/59397159/69cfc64c-9998-40b7-a097-7bc231f60939)

2023-10-17 15:31 UTC, zieeco commented on app/views/devise/sessions/new.html.erb
> +</div>
- Please, kindly update your design to be close to the main design as seen below:
   - Add the back arrow and maintain the alignment of the contents including the input and how they appear on the design.



*main sign in*
![image](https://github.com/marvin-nyalik/BudgetApp/assets/59397159/107ca8cf-2eae-4bcd-b86e-28257fabaa1c)



*your design*
![image](https://github.com/marvin-nyalik/BudgetApp/assets/59397159/f3235720-ebdf-4422-9423-401f7cda04b8)

2023-10-17 15:31 UTC, zieeco commented on app/views/devise/registrations/new.html.erb
> +</div>
- Let's also improve the sign-up page to follow the design layout, add the missing back arrow, follow the layout design of the inputs to make your design consistent following the main design:


*your design*
![image](https://github.com/marvin-nyalik/BudgetApp/assets/59397159/4c38bb19-79a8-466e-8eb2-b80c8486b61f)

*main design*
![image](https://github.com/marvin-nyalik/BudgetApp/assets/59397159/c54ee758-4457-4ec9-b40a-78d25768043c)

2023-10-17 15:31 UTC, zieeco commented on app/views/categories/index.html.erb
> +  </div>
**FOR ALL BUTTONS  FOR ADDING A TRANSACTION, ADD CATEGORY**


- Hey, kindly move your buttons to the bottom of the container and use the correct background colour as seen in the design.
- Also remove the extra added space on top of the container.

*your design*
![image](https://github.com/marvin-nyalik/BudgetApp/assets/59397159/8d9f1769-3a03-4037-a9f1-3396559eb44f)



*main design*
![image](https://github.com/marvin-nyalik/BudgetApp/assets/59397159/4fa5187e-aa12-4171-a7f1-bf8f23f45c53)

2023-10-17 15:31 UTC, zieeco commented on app/views/categories/new.html.erb
> +</div>
- Kingly remove the space at the top of the container, move the button to the bottom of the container and style the button  according using the correct background, etc.

2023-10-17 15:31 UTC, zieeco commented on app/views/categories/show.html.erb
> +<% end %>
- Hey, please, kindly remove the added space at the top of the container and move the button to the bottom of the container. Also, the button should have the correct background as seen from the main design.

2023-10-17 15:31 UTC, zieeco commented on spec/models/user_spec.rb
> +end
- Hi, you've not added any test. please, kindly add them.

2023-10-17 15:31 UTC, zieeco commented on spec/requests/purchases_spec.rb
> +end
- Hey, also kindly add some tests as you've not added anything yet.

2023-10-17 21:16 UTC, OyePriscilla requested changes
Hi @marvin-nyalik 👏 👏, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Implemented tests for users_model ✔️ 
Designed signup/sign-in in accordance to the given template ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] Kindly take note that you supposed to have opened this PR from feature branch into dev as stated in the project requirement.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-17 21:16 UTC, OyePriscilla commented on spec/requests/purchases_spec.rb
> +end
- [ ] Please as pointed out earlier, kindly ensure that you implement test for this controller (purchases.rb). This code sets up a placeholder for testing the 'GET /index' action in the 'Purchases' controller of a Rails application using RSpec. The actual test examples are yet to be written, and this code serves as a reminder for the developer to add the tests. ℹ️

2023-10-17 21:16 UTC, OyePriscilla commented on app/views/categories/new.html.erb
> +  </div>
- [ ] As raised earlier, kindly remove the top margin around this container. Designing in accordance to template shows how well we pay attention to details. ℹ️ 

<img width="259" alt="Untitled" src="https://github.com/marvin-nyalik/BudgetApp/assets/103386183/587230b1-91e5-45fd-8697-8471cae9d40e">

**Note: This is applicable to `app/views/categories/index.html.erb` and `app/views/categories/show.html.erb` files as pointed out earlier**

2023-10-18 05:45 UTC, Ibizugbe approved these changes
Hi @marvin-nyalik 👋🏼👋🏼👋🏼, 

![approved](https://github.com/marvin-nyalik/BudgetApp/assets/64643995/374eaad2-a6c9-451a-8493-c7d552047f29)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Tests cases for the purchase controller has been captured👍🏼.
- [x] Top margin has been removed from the respective pages pointed by the previous reviewers👍🏼.
- [x] All tests are passing👍🏼.

## Optional suggestions

- [OPTIONAL] Kindly take note that you are meant to make use of gitflow and not github flow for this project. reasons been that it is a solo capstone😉. Try to always look at the flow requirements before opening a PR.
<img width="513" alt="image" src="https://github.com/marvin-nyalik/BudgetApp/assets/64643995/1054d841-d072-49da-a6c9-da8cd9efeadb">


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-18 06:22 UTC, merged